apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin:latest
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        ports:
        - containerPort: 80
        env:
        - name: PMA_HOST
          value: rc1a-vldbsqvpmna4avjp.mdb.yandexcloud.net
        - name: PMA_PMADB
          value: "netology_db"
        - name: PMA_USER
          value: "user_bd"
        - name: PMA_PASSWORD
          value: "PaSSw0rd"

---

apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
spec:
  selector:
    app: phpmyadmin
  ports:
  - name: phpmyadmin
    port: 80
    protocol: TCP
    targetPort: 80
  type: LoadBalancer